const INCREMENT_COUNT = "INCREMENT_COUNT";
const DECREMENT_COUNT = "DECREMENT_COUNT";
const RESET_COUNT = "RESET_COUNT";
const INIT_LIMIT = "INIT_LIMIT";

const INCREMENT_COUNT_PRODUCT_CART = "INCREMENT_COUNT_PRODUCT_CART";
const DECREMENT_COUNT_PRODUCT_CART = "DECREMENT_COUNT_PRODUCT_CART";

const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const FETCH_CATEGORIES = "FETCH_CATEGORIES";
const GET_PRODUCT = "GET_PRODUCT";

const SET_CATEGORY = "SET_CATEGORY";
const SET_PRODUCT = "SET_PRODUCT";

const ADD_TO_CART = "ADD_TO_CART";
const DELETE_FROM_CART = "DELETE_FROM_CART";
const PRICE_CART = "PRUCE_CART";
export {
  INCREMENT_COUNT,
  DECREMENT_COUNT,
  RESET_COUNT,
  FETCH_PRODUCTS,
  FETCH_CATEGORIES,
  SET_CATEGORY,
  SET_PRODUCT,
  INIT_LIMIT,
  GET_PRODUCT,
  ADD_TO_CART,
  DELETE_FROM_CART,
  PRICE_CART,
  INCREMENT_COUNT_PRODUCT_CART,
  DECREMENT_COUNT_PRODUCT_CART
};
