const INCREMENT_COUNT = "INCREMENT_COUNT";
const DECREMENT_COUNT = "DECREMENT_COUNT";
const RESET_COUNT = "RESET_COUNT";
const INIT_LIMIT = "INIT_LIMIT";

const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const FETCH_CATEGORIES = "FETCH_CATEGORIES";

const SET_CATEGORY = "SET_CATEGORY";
const SET_PRODUCT = "SET_PRODUCT";
export {
  INCREMENT_COUNT,
  DECREMENT_COUNT,
  RESET_COUNT,
  FETCH_PRODUCTS,
  FETCH_CATEGORIES,
  SET_CATEGORY,
  SET_PRODUCT,
  INIT_LIMIT
};
