const INCREMENT_COUNT = "INCREMENT_COUNT";
const DECREMENT_COUNT = "DECREMENT_COUNT";
const RESET_COUNT = "RESET_COUNT";

const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const FETCH_CATEGORIES = "FETCH_CATEGORIES";

export {
  INCREMENT_COUNT,
  DECREMENT_COUNT,
  RESET_COUNT,
  FETCH_PRODUCTS,
  FETCH_CATEGORIES
};
